CHROME_136 = {
    "navigator": {
        "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36",
        "platform": "Win32",
        "vendor": "Google Inc.",
        "language": "zh-CN",
        "languages": ["zh-CN", "zh", "en"],
        "hardwareConcurrency": 8,
        "deviceMemory": 8,
        "maxTouchPoints": 0,
        "webdriver": False,
        "appVersion": "5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36",
        "appName": "Netscape",
        "appCodeName": "Mozilla",
        "product": "Gecko",
        "productSub": "20030107",
        "vendorSub": "",
        "cookieEnabled": True,
        "onLine": True,
        "doNotTrack": None,
    },
    "screen": {
        "width": 1920,
        "height": 1080,
        "availWidth": 1920,
        "availHeight": 1040,
        "availLeft": 0,
        "availTop": 0,
        "colorDepth": 24,
        "pixelDepth": 24,
    },
    "window": {
        "outerWidth": 1920,
        "outerHeight": 1080,
        "innerWidth": 1920,
        "innerHeight": 919,
        "screenX": 0,
        "screenY": 0,
        "pageXOffset": 0,
        "pageYOffset": 0,
        "devicePixelRatio": 1,
    },
    "location": {
        "href": "https://example.com/",
        "origin": "https://example.com",
        "protocol": "https:",
        "host": "example.com",
        "hostname": "example.com",
        "port": "",
        "pathname": "/",
        "search": "",
        "hash": "",
    },
    "document": {
        "referrer": "",
        "characterSet": "UTF-8",
        "charset": "UTF-8",
        "contentType": "text/html",
    },
}
